### PR TITLE
[mellanox] Integrate HW-MGMT 7.0030.2008 Changes

### PR DESCRIPTION
**Pull request by vivekrnv**
## Patch List
* 0172-DS-platform-mlx-platform-Add-SPI-path-for-rack-switc.patch :
* 0182-platform-mellanox-Introduce-support-of-new-Nvidia-L1.patch : https://github.com/torvalds/linux/commit/dd635e33b5c9
* 0183-platform-mellanox-Split-initialization-procedure.patch : https://github.com/torvalds/linux/commit/0170f616f496
* 0184-platform-mellanox-Split-logic-in-init-and-exit-flow.patch : https://github.com/torvalds/linux/commit/158cd8320776
* 0185-platform-mellanox-Extend-all-systems-with-I2C-notifi.patch : https://github.com/torvalds/linux/commit/233fd7e44cd7
* 0187-platform_data-mlxreg-Add-field-with-mapped-resource-.patch : https://github.com/torvalds/linux/commit/26917eab144c
* 0188-i2c-mux-Add-register-map-based-mux-driver.patch : https://patchwork.ozlabs.org/project/linux-i2c/patch/20230215195322.21955-1-vadimp@nvidia.com/
* 0189-i2c-mlxcpld-Allow-driver-to-run-on-ARM64-architectur.patch :
* 0190-i2c-mlxcpld-Support-PCIe-mapped-register-space.patch :
* 0192-i2c-mlxcpld-Add-support-for-extended-transaction-len.patch :
* 0193-platform-mellanox-mlx-platform-Add-mux-selection-reg.patch : https://github.com/torvalds/linux/commit/cefdbc7815660
* 0194-platform-mellanox-mlx-platform-Move-bus-shift-assign.patch : https://github.com/torvalds/linux/commit/50b823fdd357e
* 0195-platform-mellanox-Add-support-for-dynamic-I2C-channe.patch :
* 0196-platform-mellanox-Cosmetic-changes.patch :
* 0197-platform-mellanox-Fix-order-in-exit-flow.patch :
* 0198-platform-mellanox-Add-new-attributes.patch :
* 0199-platform-mellanox-Change-register-offset-addresses.patch :
* 0269-platform-mellanox-Add-field-upgrade-capability-regis.patch :
* 0270-platform-mellanox-Modify-reset-causes-description.patch :
* 0278-platform-mellanox-mlx-platform-Modify-graceful-shutd.patch :
* 0279-platform-mellanox-mlx-platform-Fix-signals-polarity-.patch :
* 0280-platform-mellanox-mlxreg-hotplug-Extend-condition-fo.patch :
* 0281-platform-mellanox-mlx-platform-Modify-health-and-pow.patch :
* 0282-platform-mellanox-mlx-platform-Add-reset-cause-attri.patch :
* 0284-platform-mellanox-mlx-platform-add-support-for-addit.patch :
* 0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch :
* 0295-dt-bindings-trivial-devices-Add-mps-mp2891.patch :
* 0304-platform-mellanox-mlx-platform-Modify-power-off-call.patch :
* 0305-Extend-driver-to-support-Infineon-Digital-Multi-phas.patch :
* 0311-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch :
* 0312-platform-mellanox-mlx-platform-Add-reset-callback.patch :
* 0313-platform-mellanox-mlx-platform-Prepare-driver-to-all.patch :
* 0314-platform-mellanox-mlx-platform-Introduce-ACPI-init-f.patch :
* 0315-platform-mellanox-mlx-platform-Get-interrupt-line-th.patch :
* 0316-platform-mellanox-Add-initial-support-for-PCIe-based.patch :

#### Tested branch (Please provide the tested image version)

- [x] 202305 commit https://github.com/sonic-net/sonic-buildimage/commit/40d1159b003eb73e3408ea14926d0f2c7b8790c9
- [ ]

### CODE REVIEW

**Comment by vivekrnv** [comment]
@saiarcot895 Please review

**Comment by vivekrnv** [comment]
> Is this related to the SDK update?

No hw-mgmt upgrade for 202305

**Review by dgsudharsan — APPROVED** [review]

**Review by saiarcot895 — APPROVED** [review]
Wait for approval from @StormLiangMS

**Comment by liat-grozovik** [comment]
@StormLiangMS can you please help to merge?

**Pull request merged**
