### PR TITLE
[202311] [Mellanox] Integrate HW-MGMT 7.0030.4002

### PR DESCRIPTION
**Pull request by vivekrnv**
#### What I did
- Integrate new hw-mgmt changes
- Add support for compiling linux kernel with custom platform patches and kconfig

#### How to Verify
- Compile linux kernel for mellanox and vs platforms. Make sure compilation is succeeded
- Run regression tests on mellanox platform

### CODE REVIEW

**Comment by saiarcot895** [comment]
Could you modify the `azure-pipelines.yml` pipeline to add a build for mellanox-amd64?

**Comment by vivekrnv** [comment]
> Could you modify the `azure-pipelines.yml` pipeline to add a build for mellanox-amd64?

Will update

**Review by dgsudharsan — APPROVED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@saiarcot895 @yxieca  please help to approve and merge

**Comment by yxieca** [comment]
> @saiarcot895 @yxieca please help to approve and merge

@liat-grozovik does this PR have dependency on any kernel PR?

**Comment by liat-grozovik** [comment]
@saiarcot895 Please hold the merge. we are looking into a failure we observed.

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
