### PR TITLE
[Mellanox] Add new kernel patches from HW-MGMT package V.7.0020.3005

### PR DESCRIPTION
**Pull request by keboliu**
Patch list 
- **0082-mlxsw-core-Extend-external-cooling-device-whitelist-.patch**  has not been sent to upstream yet, waiting for 0087, 0088 to be accepted, only after that we can send 0082
- **0083-platform_data-mlxreg-Add-field-for-notification-call.patch**  https://github.com/torvalds/linux/commit/abcebcd39fe094b68826cc04f2eca835606697f9
- **0084-i2c-mlxcpld-Add-callback-to-notify-probing-completio.patch**  https://patchwork.ozlabs.org/project/linux-i2c/patch/20220713091136.734-1-vadimp@nvidia.com/
- **0085-hwmon-powr1220-Upgrade-driver-to-support-hwmon-info-.patch**  https://github.com/torvalds/linux/commit/15b1c188f8cf2ff9f296c9781d1e4fc061aaf371
- **0086-hwmon-powr1220-Add-support-for-Lattice-s-POWR1014-po.patch** https://github.com/torvalds/linux/commit/9f93aa1005fa1b960f10e0ee3ed8c4e697526053
- **0087-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch** https://patchwork.kernel.org/project/linux-hwmon/patch/20220623165217.59252-2-michaelsh@nvidia.com/
- **0088-dt-bindings-Add-description-for-EMC2305-for-RPM-base.patch** https://patchwork.kernel.org/project/linux-hwmon/patch/20220623165217.59252-3-michaelsh@nvidia.com/
- **0089-platform-mellanox-Add-support-for-new-SN2201-system.patch** https://github.com/torvalds/linux/commit/662f24826f954d49d56211822bcd7b3109287961
- **0090-Documentation-ABI-Add-new-attributes-for-mlxreg-io-s.patch** https://github.com/torvalds/linux/commit/b1a9c69792caaac0813c9dc7806fb8654212e56c
- **0163-platform-mellanox-Add-COME-board-revision-register.patch**  https://patchwork.kernel.org/project/platform-driver-x86/patch/20220711084559.62447-7-vadimp@nvidia.com/
- **0167-leds-mlxreg-Send-udev-change-event.patch**     A WA to address a fan control issue on SN2201. All other Nvidia systems have fan led handling implemented in CPLD, but SN2201 doesn’t have access to FAN leds from CPLD, instead vendor DNI process FAN leds through separate i2c-gpio expander, to satisfy, this udev mechanism was invented. But this can not be upstreamed as this is can not be accepted by Linux kernel community.

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@saiarcot895 could you please help to review?

**Review by saiarcot895 — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@saiarcot895 could you please add a label for 202205?

**Comment by saiarcot895** [comment]
@liat-grozovik created the label for 202205

**Comment by liat-grozovik** [comment]
> @liat-grozovik created the label for 202205

@saiarcot895  i dont see the label set and i am not able to add one to this repo. can you please add?
@yxieca  please have it on 202205?

**Pull request merged**
