### PR TITLE
[kconfig] Set default SATA Link Power Management policy

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Between kernel 4.9 and kernel 5.10 new kconfig was introduced - CONFIG_SATA_MOBILE_LPM_POLICY.
It affects the power policy of the SSD.
In 201911 power policy was "max_performance" and it was changed by Debian 11 kernel 5.10 to "med_power_with_dipm" which allows SSD to go to sleep mode.

This change simply configures "CONFIG_SATA_MOBILE_LPM_POLICY"  to "1" which means  "max_performance".

Power policy can be checked by running  "cat /sys/class/scsi_host/host0/link_power_management_policy"

### CODE REVIEW

**Comment by volodymyrsamotiy** [comment]
Moved to draft since testing is still in progress, once testing is finished will updated PR.

**Comment by saiarcot895** [comment]
Please note that the kernel will be upgraded to 6.1 shortly. Because of that, this PR may need to be modified to be merged directly into 202305 (and backported from there), and a separate PR raised for master branch/202311 for the 6.1 kernel.

**Comment by volodymyrsamotiy** [comment]
Thanks, I created separate PRs: 202305 - https://github.com/sonic-net/sonic-linux-kernel/pull/365 & 202205 - https://github.com/sonic-net/sonic-linux-kernel/pull/366

**Comment by lguohan** [comment]
@prgeor , can you check?

**Review by prgeor — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@saiarcot895 can you please help to merge?

**Comment by paulmenzel** [comment]
What problem does this solve? Performance? On what device did you see performance issues?

**Comment by paulmenzel** [comment]
I had asked the same question in https://github.com/sonic-net/sonic-linux-kernel/pull/366.

**Pull request merged**
