### PR TITLE
[PATCH] net: allow user to set metric on default route learned via Router Advertisement

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Patch taken from Linux 5.12 to allow user to set metric on default route learned via Router Adv message for IPv6

This PR is to backport the following commits to kernel v5.10:

https://github.com/torvalds/linux/commit/6b2e04bc240fe9be9e690059f710e9f95346d34d

Why I did:

Fixes: https://github.com/sonic-net/sonic-buildimage/issues/16209

### CODE REVIEW

**Comment by abdosi** [comment]
@rlhui for viz.

**Comment by saiarcot895** [comment]
Can this patch be applied to the master branch first, and then backported from there?

**Comment by saiarcot895** [comment]
Also, please clean up the title of the PR, and add the upstream commit hash into the patch.

**Comment by abdosi** [comment]
> Can this patch be applied to the master branch first, and then backported from there?

as the master will be moving to new Debian with Linux 6.1 do we still want to take it into master  ?

**Comment by rlhui** [comment]
@abdosi is it correct that this one is closed?

**Pull request closed without merging**
