### PR TITLE
[marvell-arm64]: Update kernel patches for Linux 6.1.x

### PR DESCRIPTION
**Pull request by Keshavg-marvell**
This patch ports the marvel patches to bookworm kernel and updates the series file to remove upstreamed patches. Also the new order of patches is created in series file.

It fixes https://github.com/sonic-net/sonic-buildimage/issues/16865

### CODE REVIEW

**Comment by Keshavg-marvell** [comment]
@Pavan-Nokia please review

**Comment by paulmenzel** [comment]
Please elaborate in the git commit message, and also add notes how the remaining patches are going to be upstreamed.

**Comment by saiarcot895** [comment]
@Keshavg-marvell As Paul mentioned, is there any update on the upstreaming of the remaining patches?

**Comment by Keshavg-marvell** [comment]
For the up-streamed commits we are addressing one by one. 
To start with for sonic-linux-kernel PR https://github.com/sonic-net/sonic-linux-kernel/pull/337 - the below PR is raised against  kernel.org 
https://lore.kernel.org/linux-devicetree/20231024131935.2567969-1-enachman@marvell.com/T/#u

**Comment by Keshavg-marvell** [comment]
The changes  here in this PR are the existing patches and adapted to new kernel which were not getting applied cleanly
due to api, api-signature, file format changes etc in new kernel. Here we are also renumbering
series file. So due to file renaming and resolution of patch somehow for some of patch git 
is taking it as deleted and added instead of showing renamed.  
for ex below patch.  
"patch/0016-ac5-marvell-Add-support-for-emmc.patch (showing deleted)  -> patch/0006-ac5-marvell-Add-support-for-emmc.patch (added)"

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
