### PR TITLE
arm64: Enable CONFIG_KEXEC_FILE

### PR DESCRIPTION
**Pull request by pavannaregundi**
This change enables CONFIG_KEXEC_FILE to make kexec_file_load() system call available. This functionality is needed for warm-reboot support. Warm reboot scripts invokes kexec load which uses file based syscall. 

On amd64 builds this is already enabled, but see it disabled on arm64.

Changes also needs to be cherry picked to 202211 branch.

Change-Id: Iaf10e1a153bbac2e344d0c9646e7fa1fe5f7429d

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Comment by pavannaregundi** [comment]
@saiarcot895 Can we cherry pick this PR for 202211.

**Comment by yxieca** [comment]
@pavannaregundi this change cannot be cherry-picked to 202211 cleanly. Please create separate PR.

**Comment by pavannaregundi** [comment]
> @pavannaregundi this change cannot be cherry-picked to 202211 cleanly. Please create separate PR.

https://github.com/sonic-net/sonic-linux-kernel/pull/351 has been raise for this. Please review and merge.

**Comment by StormLiangMS** [comment]
@pavannaregundi this change cannot be cherry-picked to 202305 cleanly. Please create separate PR.

**Comment by pavannaregundi** [comment]
> @pavannaregundi this change cannot be cherry-picked to 202305 cleanly. Please create separate PR.

https://github.com/sonic-net/sonic-linux-kernel/pull/351 is raised 202305.

**Pull request merged**
