### PR TITLE
[202205] Add Secure Boot Kernel configuration

### PR DESCRIPTION
**Pull request by sacnaik**
Backporting #298, the kernel module signing/verification support from the master branch.

These patches are needed to enable secure boot on the 202205 branch.

The change also includes additional patches which are added in manage-config to apply #298 patch without any issues and as a dependent patch.

See
sonic-buildimage PR link: https://github.com/sonic-net/sonic-buildimage/pull/12692
HLD: https://github.com/sonic-net/SONiC/pull/1028

### CODE REVIEW

**Comment by paulmenzel** [comment]
Please update the merge/pull request message summary/title.

**Comment by rlhui** [comment]
@davidpil2002 , please help review

**Comment by sacnaik** [comment]
@paulmenzel, Sorry it's not clear to me "Please update the merge/pull request message summary/title." 
Are you saying the update is needed on the conversation tab??  also not clear what info needs to be updated.

**Comment by paulmenzel** [comment]
I mean the title *Sachnaik/kosigning*. There is an edit button next to it on the right side. Maybe use:

> [202205] Add Secure Boot Kernel configuration

**Comment by sacnaik** [comment]
Thanks. Updated it.

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
