### PR TITLE
Fix RCU stall detected in kernel 6.1 when unregistering devlink

### PR DESCRIPTION
**Pull request by vivekrnv**
Resolves: https://github.com/sonic-net/sonic-buildimage/issues/20368

Ref: https://lore.kernel.org/stable/20241001112035.973187-1-idosch@nvidia.com/t/#u

> But first of, why? Why not just take the upstrema commits instead?
> 
> thanks,
> greg k-h

Ido:

> There were a lot of changes as part of the 6.3 cycle to completely
> rework the semantics of the devlink instance reference count. As part of
> these changes, commit d77278196441 ("devlink: bump the instance index
> directly when iterating") inadvertently fixed the bug mentioned in this
> patch. This commit cannot be applied to 6.1.y as-is because a prior
> commit (also in 6.3) moved the code to a different file (leftover.c ->
> core.c). There might be more dependencies that I'm currently unaware of.
> 
> The alternative, proposed in this patch, is to provide a minimal and
> contained fix for the bug introduced in upstream commit c2368b19807a
> ("net: devlink: introduce "unregistering" mark and use it during
> devlinks iteration") as part of the 6.0 cycle.

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by saiarcot895 — APPROVED** [review]
Upstream kernel maintainers are in favor of backporting changes from master branch to the 6.1 stable branch instead of having a standalone/new commits on a stable branch (which makes sense in terms of maintenance and stability). However, this may mean backporting an unknown number of patches.

For the sake of simplicity, I'm in favor of backporting a single patch.

**Comment by paulmenzel** [comment]
> Fix: https://github.com/sonic-net/sonic-buildimage/issues/20368

I’d use the tag *Resolves:*.

> Ref: https://lore.kernel.org/stable/20241001112035.973187-1-idosch@nvidia.com/t/#u

Please summarize the discussion. Best take @idosch’s explanation from his first reply to Greg.

**Comment by vivekrnv** [comment]
> But first of, why?  Why not just take the upstrema commits instead?
> 
> thanks,
> greg k-h

Ido:
> There were a lot of changes as part of the 6.3 cycle to completely
> rework the semantics of the devlink instance reference count. As part of
> these changes, commit d77278196441 ("devlink: bump the instance index
> directly when iterating") inadvertently fixed the bug mentioned in this
> patch. This commit cannot be applied to 6.1.y as-is because a prior
> commit (also in 6.3) moved the code to a different file (leftover.c ->
> core.c). There might be more dependencies that I'm currently unaware of.
> 
> The alternative, proposed in this patch, is to provide a minimal and
> contained fix for the bug introduced in upstream commit c2368b19807a
> ("net: devlink: introduce "unregistering" mark and use it during
> devlinks iteration") as part of the 6.0 cycle.

Summary of https://lore.kernel.org/stable/20241001112035.973187-1-idosch@nvidia.com/t/#u

**Comment by vivekrnv** [comment]
@bingwang-ms Can this me merged?

**Pull request merged**
