### PR TITLE
[Bookworm] Rebase latest linux kernel changes

### PR DESCRIPTION
**Pull request by vivekrnv**

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Comment by vivekrnv** [comment]
@saiarcot895 can we merge this?

**Comment by paulmenzel** [comment]
Why not merge the master branch instead?

**Comment by paulmenzel** [comment]
It’d be great if you shared your rebase command.

**Comment by saiarcot895** [comment]
@paulmenzel This was to resolve some conflicts that would occur with the next rebase onto the top of the master branch. The rebase was done through Github's UI (there's an option to do a rebase and merge on top of the target branch).

**Comment by saiarcot895** [comment]
This branch will get merged into master branch in the near future as well.

**Pull request merged**
