### PR TITLE
[202205] [kconfig] Set default SATA Link Power Management policy

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
Between kernel 4.9 and kernel 5.10 new kconfig was introduced - CONFIG_SATA_MOBILE_LPM_POLICY.
It affects the power policy of the SSD.
In 201911 power policy was "max_performance" and it was changed by Debian 11 kernel 5.10 to "med_power_with_dipm" which allows SSD to go to sleep mode.

This change simply configures "CONFIG_SATA_MOBILE_LPM_POLICY" to "1" which means "max_performance".

Power policy can be checked by running "cat /sys/class/scsi_host/host0/link_power_management_policy"

### CODE REVIEW

**Review by saiarcot895 — APPROVED** [review]

**Review by paulmenzel — CHANGES_REQUESTED** [review]
Saving power is a good thing today, so without a good reason I am against changing defaults for all devices. The commit message does not even say, what the problem is, and also does not mention a device.

**Comment by yxieca** [comment]
> Saving power is a good thing today, so without a good reason I am against changing defaults for all devices. The commit message does not even say, what the problem is, and also does not mention a device.

@volodymyrsamotiy can you add the missing information? Please elaborate the issue and the necessity of having this change.

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@yxieca please merge to fix SATA issue

**Comment by liat-grozovik** [comment]
@saiarcot895 can you please help to merge?

**Comment by saiarcot895** [comment]
@volodymyrsamotiy Please add details of the issue to this PR and to #363 (which has already been merged).

**Comment by prgeor** [comment]
> Saving power is a good thing today, so without a good reason I am against changing defaults for all devices. The commit message does not even say, what the problem is, and also does not mention a device.

@paulmenzel  This is causing file-system read-only issue with few SATA disk vendors, errors like:-

```
2023-10-24T12:30:37Z        <3>Oct 24 12:30:39 SJC22-0101-0510-17T1 kernel: [1601766.533875] ata1: SError: { UnrecovData CommWake LinkSeq }
2023-10-24T12:30:37Z        <3>Oct 24 12:30:39 SJC22-0101-0510-17T1 kernel: [1601766.533881] ata1.00: failed command: WRITE FPDMA QUEUED
2023-10-24T12:30:37Z        <3>Oct 24 12:30:39 SJC22-0101-0510-17T1 kernel: [1601766.533892] ata1.00: cmd 61/10:40:30:a6:14/00:00:01:00:00/40 tag 8 ncq dma 8192 out
2023-10-24T12:30:37Z        <3>Oct 24 12:30:39 SJC22-0101-0510-17T1 kernel: [1601766.533895] ata1.00: status: { DRDY }
2023-10-24T13:40:59Z        <3>Oct 24 13:41:02 SJC22-0101-0510-17T1 kernel: [1605988.625549] ata1.00: exception Emask 0x10 SAct 0x1 SErr 0x440100 action 0x6 frozen
2023-10-24T13:40:59Z        <3>Oct 24 13:41:02 SJC22-0101-0510-17T1 kernel: [1605988.625554] ata1.00: irq_stat 0x08000000, interface fatal error
2023-10-24T13:40:59Z        <3>Oct 24 13:41:02 SJC22-0101-0510-17T1 kernel: [1605988.625557] ata1: SError: { UnrecovData CommWake Handshk }
```

**Pull request merged**
