### PR TITLE
[202311] [Mellanox] Integrate HW-MGMT 7.0030.2008 Changes

### PR DESCRIPTION
**Pull request by keboliu**
This is to backport https://github.com/sonic-net/sonic-linux-kernel/pull/361 to 202311

 ## Patch List
* 0172-DS-platform-mlx-platform-Add-SPI-path-for-rack-switc.patch :
* 0182-platform-mellanox-Introduce-support-of-new-Nvidia-L1.patch : https://github.com/torvalds/linux/commit/dd635e33b5c9
* 0183-platform-mellanox-Split-initialization-procedure.patch : https://github.com/torvalds/linux/commit/0170f616f496
* 0184-platform-mellanox-Split-logic-in-init-and-exit-flow.patch : https://github.com/torvalds/linux/commit/158cd8320776
* 0185-platform-mellanox-Extend-all-systems-with-I2C-notifi.patch : https://github.com/torvalds/linux/commit/233fd7e44cd7
* 0187-platform_data-mlxreg-Add-field-with-mapped-resource-.patch : https://github.com/torvalds/linux/commit/26917eab144c
* 0188-i2c-mux-Add-register-map-based-mux-driver.patch : https://patchwork.ozlabs.org/project/linux-i2c/patch/20230215195322.21955-1-vadimp@nvidia.com/
* 0189-i2c-mlxcpld-Allow-driver-to-run-on-ARM64-architectur.patch :
* 0190-i2c-mlxcpld-Support-PCIe-mapped-register-space.patch :
* 0192-i2c-mlxcpld-Add-support-for-extended-transaction-len.patch :
* 0193-platform-mellanox-mlx-platform-Add-mux-selection-reg.patch : https://github.com/torvalds/linux/commit/cefdbc7815660
* 0194-platform-mellanox-mlx-platform-Move-bus-shift-assign.patch : https://github.com/torvalds/linux/commit/50b823fdd357e
* 0195-platform-mellanox-Add-support-for-dynamic-I2C-channe.patch :
* 0196-platform-mellanox-Cosmetic-changes.patch :
* 0197-platform-mellanox-Fix-order-in-exit-flow.patch :
* 0198-platform-mellanox-Add-new-attributes.patch :
* 0199-platform-mellanox-Change-register-offset-addresses.patch :
* 0269-platform-mellanox-Add-field-upgrade-capability-regis.patch :
* 0270-platform-mellanox-Modify-reset-causes-description.patch :
* 0278-platform-mellanox-mlx-platform-Modify-graceful-shutd.patch :
* 0279-platform-mellanox-mlx-platform-Fix-signals-polarity-.patch :
* 0280-platform-mellanox-mlxreg-hotplug-Extend-condition-fo.patch :
* 0281-platform-mellanox-mlx-platform-Modify-health-and-pow.patch :
* 0282-platform-mellanox-mlx-platform-Add-reset-cause-attri.patch :
* 0284-platform-mellanox-mlx-platform-add-support-for-addit.patch :
* 0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch :
* 0295-dt-bindings-trivial-devices-Add-mps-mp2891.patch :
* 0304-platform-mellanox-mlx-platform-Modify-power-off-call.patch :
* 0305-Extend-driver-to-support-Infineon-Digital-Multi-phas.patch :
* 0311-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch :
* 0312-platform-mellanox-mlx-platform-Add-reset-callback.patch :
* 0313-platform-mellanox-mlx-platform-Prepare-driver-to-all.patch :
* 0314-platform-mellanox-mlx-platform-Introduce-ACPI-init-f.patch :
* 0315-platform-mellanox-mlx-platform-Get-interrupt-line-th.patch :
* 0316-platform-mellanox-Add-initial-support-for-PCIe-based.patch :

### CODE REVIEW

**Comment by saiarcot895** [comment]
There are errors in the arm64 and armhf build.

arm64 errors:

```
Option CONFIG_MLX_PLATFORM should be set to [m] instead of [undef]
Option CONFIG_REGMAP_I2C should be set to [m] instead of [y]
Option CONFIG_GPIO_GENERIC should be set to [m] instead of [y]
```

armhf errors:

```
Option CONFIG_I2C_MUX should be set to [m] instead of [y]
Option CONFIG_I2C_MLXCPLD should be set to [m] instead of [undef]
Option CONFIG_MLX_PLATFORM should be set to [m] instead of [undef]
Option CONFIG_REGMAP_I2C should be set to [m] instead of [y]
Option CONFIG_GPIO_GENERIC should be set to [m] instead of [y]
```

**Comment by keboliu** [comment]
> There are errors in the arm64 and armhf build.
> 
> arm64 errors:
> 
> ```
> Option CONFIG_MLX_PLATFORM should be set to [m] instead of [undef]
> Option CONFIG_REGMAP_I2C should be set to [m] instead of [y]
> Option CONFIG_GPIO_GENERIC should be set to [m] instead of [y]
> ```
> 
> armhf errors:
> 
> ```
> Option CONFIG_I2C_MUX should be set to [m] instead of [y]
> Option CONFIG_I2C_MLXCPLD should be set to [m] instead of [undef]
> Option CONFIG_MLX_PLATFORM should be set to [m] instead of [undef]
> Option CONFIG_REGMAP_I2C should be set to [m] instead of [y]
> Option CONFIG_GPIO_GENERIC should be set to [m] instead of [y]
> ```

Thanks, will investigate.

**Comment by keboliu** [comment]
> There are errors in the arm64 and armhf build.
> 
> arm64 errors:
> 
> ```
> Option CONFIG_MLX_PLATFORM should be set to [m] instead of [undef]
> Option CONFIG_REGMAP_I2C should be set to [m] instead of [y]
> Option CONFIG_GPIO_GENERIC should be set to [m] instead of [y]
> ```
> 
> armhf errors:
> 
> ```
> Option CONFIG_I2C_MUX should be set to [m] instead of [y]
> Option CONFIG_I2C_MLXCPLD should be set to [m] instead of [undef]
> Option CONFIG_MLX_PLATFORM should be set to [m] instead of [undef]
> Option CONFIG_REGMAP_I2C should be set to [m] instead of [y]
> Option CONFIG_GPIO_GENERIC should be set to [m] instead of [y]
> ```

Fixed, thanks.

**Comment by keboliu** [comment]
@saiarcot895  @yxieca would you please help to merge this PR?

**Review by saiarcot895 — APPROVED** [review]

**Comment by keboliu** [comment]
@yxieca would you please help to merge?

**Pull request merged**
