### PR TITLE
Bookworm:AMD-Pensando ELBA SOC support

### PR DESCRIPTION
**Pull request by shanshri**
This is a change request for updating the kernel patches for AMD-Pensando ELBA SOC to linux 6.1 based bookworm.

The patches has been refactored in line with the latest kernel patches released by pensando linux team

Elba provides a secure, controlled portal to network services,
storage, and the data center control plane.
This SOC is used in AMD-Pensando PCI Distributed Services Card (DSC).

The changes are verified on Pensando DSC2-200 card.

### CODE REVIEW

**Review by paulmenzel — CHANGES_REQUESTED** [review]
Thank you for your patch. Please add a commit message and merge/pull request description.

**Comment by saiarcot895** [comment]
@shanshri Please sign the EasyCLA.

**Comment by shanshri** [comment]
> @shanshri Please sign the EasyCLA.

@saiarcot895 we are looking into signing corporate CLA for AMD.

**Comment by shanshri** [comment]
> > @shanshri Please sign the EasyCLA.
> 
> @saiarcot895 we are looking into signing corporate CLA for AMD.

@saiarcot895 signed the CLA

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
