### PR TITLE
[Micas] Enable CONFIG_SENSORS_ISL68137 and CONFIG_SENSORS_INA3221 

### PR DESCRIPTION
**Pull request by philo-micas**
Help enable below Macros:
CONFIG_SENSORS_ISL68137: sensor chip of isl68137 series
CONFIG_SENSORS_INA3221: ina3221 series sensor chips

### CODE REVIEW

**Comment by philo-micas** [comment]
@paulmenzel @lguohan @prgeor @saiarcot895  Help arrange review for this PR, thanks!

**Comment by paulmenzel** [comment]
> They are independent macros that require support from kernel drivers

Macros?

Please elaborate. What device? How did you test, that the devices work now?

**Comment by paulmenzel** [comment]
Please rebase your branch instead of merging the branch *master* into it.

**Comment by philo-micas** [comment]
> Please rebase your branch instead of merging the branch _master_ into it.

OK， I have executed ‘git rebase origin/master’ and ‘git push’ again，thanks.

**Comment by paulmenzel** [comment]
No idea, why more commits are shown on GitHub.

It’d be nice, if you amended the merge/pull request description.

**Comment by philo-micas** [comment]
> No idea, why more commits are shown on GitHub.
> 
> It’d be nice, if you amended the merge/pull request description.

Due to a misoperation, the PR was closed. I have resubmitted a new PR(https://github.com/sonic-net/sonic-linux-kernel/pull/419). Could you please push it forward again.

**Comment by philo-micas** [comment]
> No idea, why more commits are shown on GitHub.
> 
> It’d be nice, if you amended the merge/pull request description.

Has updated. @paulmenzel @saiarcot895 Help arrange review for this PR, thanks!

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
