### PR TITLE
[marvell-arm64]: Add kernel patches and kconfig change

### PR DESCRIPTION
**Pull request by pavannaregundi**
These patches add necessary support for marvell platforms - 98DX35xx and 98CX85xx.

Change-Id: Ia4752c461dcf863331b38b7456b52430d8369d3f
Signed-off-by: Pavan Naregundi <pnaregundi@marvell.com>

### CODE REVIEW

**Review by paulmenzel — CHANGES_REQUESTED** [review]
> These patches add necessary support for marvell platforms 98DX35xx, 98cx85xx.

Please spell DX/CX consistently.

How was it tested?

Please split the one commit, and add commits for the Kconfig changes, detailing why these were necessary.

**Comment by pavannaregundi** [comment]
Will breakdown the review into two or more PRs. Closing this.

**Comment by paulmenzel** [comment]
Please reuse this merge/pull request, as those can contain several commits. Just split the one commit into several ones ([with descriptive and understandable commit message](https://cbea.ms/git-commit/)).

**Comment by pavannaregundi** [comment]
@paulmenzel I have raised https://github.com/sonic-net/sonic-linux-kernel/pull/307 to better organize patches per platform. Please review.

**Pull request closed without merging**
