### PR TITLE
Remove kernel config SERIAL_8250_RUNTIME_UARTS

### PR DESCRIPTION
**Pull request by madhava28**
Issue:
UART parameter of Cisco linux kernel configuration will cause Accton platform
not to dump any message on booting stage.

Fix:
Remove SERIAL_8250_RUNTIME_UARTS config. This will be passed as bootargs to the
kernel during bootup.

Signed-off-by: Madhava Reddy Siddareddygari <msiddare@cisco.com>

### CODE REVIEW

**Review by lguohan — APPROVED** [review]

**Comment by paulmenzel** [comment]
Please elaborate the problem. What Accton platform fails to boot, and what is the reason.

What is now happening with the Cisco devices? Will they still work? Why was the value set to 32 in the first place?

**Review by paulmenzel — CHANGES_REQUESTED** [review]
Updating GitHub meta data.

**Comment by lguohan** [comment]
here is the issue. https://github.com/Azure/sonic-buildimage/issues/11238

the plan is that cisco will revert this one, and then use bootargs to set it up only for cisco platforms.

**Review by paulmenzel — CHANGES_REQUESTED** [review]
Thank you. Please amend the commit message with a summary of the issue in the commit message, add document Linux CLI parameter name.

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
